sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1

install: npm install

before_script:
  - greenkeeper-lockfile-update
  - npm run build

after_script: greenkeeper-lockfile-upload
